import type { CanvasState } from "@/hooks/useDesignCanvasState";
// import { DEFAULT_META } from "@/hooks/useDesignCanvasState";

// export const DEMO_FLOOR_PLAN: CanvasState = {
// export const DEMO_FLOOR_PLAN: CanvasState = {
//   meta: {
//     version: 1,
//     unit: "m",
//     defaultWallHeight: 3,
//     defaultWallThickness: 0.25,
//     defaultInnerWallThickness: 0.15,
//     slabThickness: 0.2,
//     floorLevel: 0,
//     projectName: "Villa — Variant A Courtyard Spine",
//   },
//   rooms: [
//     {
//       id: "majlis",
//       label: "Majlis (Living Room)",
//       x: 3.5,
//       y: 20,
//       width: 6,
//       height: 5,
//       floor: {
//         color: "#e4d7c5",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "foyer",
//       label: "Entry Foyer",
//       x: 9.5,
//       y: 22,
//       width: 3,
//       height: 3,
//       floor: {
//         color: "#efe8dc",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "prayer",
//       label: "Prayer Room",
//       x: 3.5,
//       y: 17,
//       width: 3,
//       height: 3,
//       floor: {
//         color: "#d9cbb3",
//         material: "carpet",
//       },
//     },
//     {
//       id: "bathroom1",
//       label: "Bathroom 1",
//       x: 6.5,
//       y: 17,
//       width: 3,
//       height: 2.5,
//       floor: {
//         color: "#d7dde2",
//         material: "ceramic",
//       },
//     },
//     {
//       id: "stairs1",
//       label: "Straight Stair",
//       x: 9.5,
//       y: 17,
//       width: 3,
//       height: 5,
//       floor: {
//         color: "#d8d8d8",
//         material: "stone",
//       },
//     },
//     {
//       id: "elevator1",
//       label: "Elevator",
//       x: 12.8,
//       y: 20,
//       width: 2,
//       height: 2,
//       floor: {
//         color: "#cccccc",
//         material: "tile",
//       },
//     },
//     {
//       id: "courtyard",
//       label: "Courtyard",
//       x: 10,
//       y: 13.5,
//       width: 4,
//       height: 4,
//       floor: {
//         color: "#cbbf9d",
//         material: "stone",
//       },
//     },
//     {
//       id: "family_living_dining",
//       label: "Family Living + Dining",
//       x: 14,
//       y: 15,
//       width: 7.5,
//       height: 7,
//       floor: {
//         color: "#eadfcb",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "kitchen",
//       label: "Kitchen",
//       x: 17,
//       y: 10.5,
//       width: 4.5,
//       height: 4.5,
//       floor: {
//         color: "#f0f0f0",
//         material: "anti-slip tile",
//       },
//     },
//     {
//       id: "maids_room",
//       label: "Maid's Room",
//       x: 14,
//       y: 10.5,
//       width: 3,
//       height: 3,
//       floor: {
//         color: "#e6e1d6",
//         material: "vinyl",
//       },
//     },
//     {
//       id: "storage",
//       label: "Storage",
//       x: 14,
//       y: 8.5,
//       width: 2,
//       height: 2,
//       floor: {
//         color: "#dcdcdc",
//         material: "tile",
//       },
//     },
//     {
//       id: "bedroom1",
//       label: "Bedroom 1",
//       x: 3.5,
//       y: 11.5,
//       width: 4.5,
//       height: 5,
//       floor: {
//         color: "#e8d5b7",
//         material: "wood-look tile",
//       },
//     },
//     {
//       id: "bedroom2",
//       label: "Bedroom 2",
//       x: 8.5,
//       y: 8.5,
//       width: 4.5,
//       height: 4.5,
//       floor: {
//         color: "#e8d5b7",
//         material: "wood-look tile",
//       },
//     },
//     {
//       id: "master_bedroom",
//       label: "Bedroom 3 (Master)",
//       x: 3.5,
//       y: 6,
//       width: 5.5,
//       height: 4.5,
//       floor: {
//         color: "#e6d0b0",
//         material: "wood-look tile",
//       },
//     },
//     {
//       id: "bathroom2",
//       label: "Bathroom 2",
//       x: 16,
//       y: 8.5,
//       width: 3,
//       height: 2.5,
//       floor: {
//         color: "#d7dde2",
//         material: "ceramic",
//       },
//     },
//     {
//       id: "hall",
//       label: "Hall / Corridor",
//       x: 9,
//       y: 6,
//       width: 5,
//       height: 7.5,
//       floor: {
//         color: "#ece6db",
//         material: "porcelain",
//       },
//     },
//   ],
//   walls: [
//     {
//       id: "ow-n",
//       x1: 3.5,
//       y1: 25,
//       x2: 21.5,
//       y2: 25,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-e",
//       x1: 21.5,
//       y1: 6,
//       x2: 21.5,
//       y2: 25,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-s",
//       x1: 3.5,
//       y1: 6,
//       x2: 21.5,
//       y2: 6,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-w",
//       x1: 3.5,
//       y1: 6,
//       x2: 3.5,
//       y2: 25,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "iw-1",
//       x1: 9.5,
//       y1: 17,
//       x2: 9.5,
//       y2: 25,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "iw-2",
//       x1: 14,
//       y1: 8.5,
//       x2: 14,
//       y2: 22,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "iw-3",
//       x1: 3.5,
//       y1: 17,
//       x2: 14,
//       y2: 17,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "iw-4",
//       x1: 14,
//       y1: 15,
//       x2: 21.5,
//       y2: 15,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//   ],
//   doors: [
//     {
//       id: "door-main",
//       x: 11,
//       y: 25,
//       width: 1.6,
//       height: 2.4,
//       wallId: "ow-n",
//       rotation: 180,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 100,
//     },
//     {
//       id: "door-majlis",
//       x: 9.5,
//       y: 22,
//       width: 1.2,
//       height: 2.2,
//       wallId: "iw-1",
//       rotation: 90,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//     {
//       id: "door-family",
//       x: 14,
//       y: 18,
//       width: 1.5,
//       height: 2.4,
//       wallId: "iw-2",
//       rotation: 90,
//       type: "sliding",
//       openDirection: "left",
//       swingAngle: 0,
//     },
//     {
//       id: "door-kitchen",
//       x: 18,
//       y: 15,
//       width: 1,
//       height: 2.2,
//       wallId: "iw-4",
//       rotation: 180,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "door-bed1",
//       x: 8,
//       y: 13,
//       width: 0.95,
//       height: 2.2,
//       wallId: "iw-3",
//       rotation: 180,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//   ],
//   windows: [
//     {
//       id: "win-majlis-n",
//       x1: 4.2,
//       y1: 25,
//       x2: 7.2,
//       y2: 25,
//       height: 1.5,
//       sillHeight: 0.9,
//       wallId: "ow-n",
//     },
//     {
//       id: "win-foyer-n",
//       x1: 10.2,
//       y1: 25,
//       x2: 11.8,
//       y2: 25,
//       height: 1.5,
//       sillHeight: 1.1,
//       wallId: "ow-n",
//     },
//     {
//       id: "win-family-e",
//       x1: 21.5,
//       y1: 16.2,
//       x2: 21.5,
//       y2: 19.8,
//       height: 1.6,
//       sillHeight: 0.8,
//       wallId: "ow-e",
//     },
//     {
//       id: "win-kitchen-e",
//       x1: 21.5,
//       y1: 11.5,
//       x2: 21.5,
//       y2: 13.5,
//       height: 1.2,
//       sillHeight: 1.2,
//       wallId: "ow-e",
//     },
//     {
//       id: "win-bed1-w",
//       x1: 3.5,
//       y1: 12.5,
//       x2: 3.5,
//       y2: 14.5,
//       height: 1.4,
//       sillHeight: 1,
//       wallId: "ow-w",
//     },
//     {
//       id: "win-master-s",
//       x1: 5,
//       y1: 6,
//       x2: 7.2,
//       y2: 6,
//       height: 1.4,
//       sillHeight: 1,
//       wallId: "ow-s",
//     },
//   ],
//   stairs: [
//     {
//       id: "stairs-1",
//       x: 9.5,
//       y: 17,
//       width: 3,
//       height: 5,
//       direction: "up",
//     },
//   ],
//   furniture: [],
//   // areaCalc: {
//   //   plotArea: 750,
//   //   buildableEnvelopeArea: 462,
//   //   footprintArea: 342,
//   //   openCourtyardArea: 16,
//   //   enclosedBuiltArea: 326,
//   //   estimatedCirculationAndWallArea: 106.75,
//   //   roomAreas: {
//   //     majlis: 30,
//   //     foyer: 9,
//   //     prayer: 9,
//   //     bathroom1: 7.5,
//   //     family_living_dining: 52.5,
//   //     kitchen: 20.25,
//   //     maids_room: 9,
//   //     storage: 4,
//   //     bedroom1: 22.5,
//   //     bedroom2: 20.25,
//   //     master_bedroom: 24.75,
//   //     bathroom2: 7.5,
//   //     hall: 37.5,
//   //     stairs: 15,
//   //     elevator: 4,
//   //     courtyard: 16,
//   //   },
//   //   parkingAreaReserved: 30,
//   //   estimatedConstructionCost: 489000,
//   //   budgetCheck: {
//   //     withinBudget: true,
//   //     budget: 750000,
//   //     estimatedCost: 489000,
//   //     remainingAllowance: 261000,
//   //   },
//   // },
//   // designRationale:
//   //   "Variant A uses a central courtyard spine to bring daylight into the middle of the house while preserving high privacy. Public functions are placed to the north for formal access, with the Majlis and guest reception near the main entrance. Family living, dining, and kitchen are grouped to the east and southeast in an open-plan arrangement. Bedrooms are pushed to the south and southwest for privacy. Windows are limited on exposed hot facades and are larger on north and east sides to support daylight and natural ventilation from prevailing NW winds. RC structure, insulated wall assembly, R13 insulation, central AC, elevator, and straight stair are included.",
// };

export const DEMO_FLOOR_PLAN: CanvasState = {
  meta: {
    version: 1,
    unit: "m",
    defaultWallHeight: 3.0,
    defaultWallThickness: 0.25,
    defaultInnerWallThickness: 0.15,
    slabThickness: 0.18,
    floorLevel: 0.0,
    projectName: "Villa — Variant A — Central Courtyard",
  },
  rooms: [
    {
      id: "A-majlis",
      label: "Majlis (Living Room)",
      x: 3.0,
      y: 20.0,
      width: 7.0,
      height: 5.0,
      // area: 35.0,
      floor: {
        color: "#d9d4c7",
        material: "porcelain",
      },
    },
    {
      id: "A-guest-lobby",
      label: "Guest Reception Lobby",
      x: 10.0,
      y: 20.0,
      width: 4.0,
      height: 5.0,
      // area: 20.0,
      floor: {
        color: "#e7e2d8",
        material: "porcelain",
      },
    },
    {
      id: "A-prayer",
      label: "Prayer Room",
      x: 14.0,
      y: 20.0,
      width: 4.0,
      height: 5.0,
      // area: 20.0,
      floor: {
        color: "#cbbf9d",
        material: "carpet",
      },
    },
    {
      id: "A-core",
      label: "Core / Security / Elevator Lobby",
      x: 18.0,
      y: 20.0,
      width: 4.0,
      height: 5.0,
      // area: 20.0,
      floor: {
        color: "#dfe3e6",
        material: "porcelain",
      },
    },
    {
      id: "A-family",
      label: "Family Living",
      x: 3.0,
      y: 15.0,
      width: 7.0,
      height: 5.0,
      // area: 35.0,
      floor: {
        color: "#d8c8b2",
        material: "wood-look porcelain",
      },
    },
    {
      id: "A-courtyard",
      label: "Courtyard",
      x: 10.0,
      y: 15.0,
      width: 4.0,
      height: 5.0,
      // area: 20.0,
      // openToSky: true,
      floor: {
        color: "#c9b79c",
        material: "stone",
      },
    },
    {
      id: "A-dining",
      label: "Dining",
      x: 14.0,
      y: 15.0,
      width: 4.0,
      height: 5.0,
      // area: 20.0,
      floor: {
        color: "#d8c8b2",
        material: "wood-look porcelain",
      },
    },
    {
      id: "A-kitchen",
      label: "Kitchen",
      x: 18.0,
      y: 15.0,
      width: 4.0,
      height: 5.0,
      // area: 20.0,
      floor: {
        color: "#e2e2de",
        material: "porcelain",
      },
    },
    {
      id: "A-master",
      label: "Bedroom 1 (Master)",
      x: 3.0,
      y: 9.0,
      width: 7.0,
      height: 6.0,
      // area: 42.0,
      floor: {
        color: "#cdb89d",
        material: "wood-look porcelain",
      },
    },
    {
      id: "A-bath-1",
      label: "Bathroom 1",
      x: 10.0,
      y: 9.0,
      width: 4.0,
      height: 3.0,
      // area: 12.0,
      floor: {
        color: "#d8dde0",
        material: "anti-slip porcelain",
      },
    },
    {
      id: "A-bath-2",
      label: "Bathroom 2",
      x: 10.0,
      y: 12.0,
      width: 4.0,
      height: 3.0,
      // area: 12.0,
      floor: {
        color: "#d8dde0",
        material: "anti-slip porcelain",
      },
    },
    {
      id: "A-bed-2",
      label: "Bedroom 2",
      x: 14.0,
      y: 9.0,
      width: 4.0,
      height: 6.0,
      // area: 24.0,
      floor: {
        color: "#cfbea8",
        material: "wood-look porcelain",
      },
    },
    {
      id: "A-bed-3",
      label: "Bedroom 3",
      x: 18.0,
      y: 9.0,
      width: 4.0,
      height: 6.0,
      // area: 24.0,
      floor: {
        color: "#cfbea8",
        material: "wood-look porcelain",
      },
    },
  ],
  walls: [
    {
      id: "A-ow-s",
      x1: 3.0,
      y1: 9.0,
      x2: 22.0,
      y2: 9.0,
      thickness: 0.25,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.25,
    },
    {
      id: "A-ow-e",
      x1: 22.0,
      y1: 9.0,
      x2: 22.0,
      y2: 25.0,
      thickness: 0.25,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.25,
    },
    {
      id: "A-ow-n",
      x1: 22.0,
      y1: 25.0,
      x2: 3.0,
      y2: 25.0,
      thickness: 0.25,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.25,
    },
    {
      id: "A-ow-w",
      x1: 3.0,
      y1: 25.0,
      x2: 3.0,
      y2: 9.0,
      thickness: 0.25,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.25,
    },
    {
      id: "A-i-v1",
      x1: 10.0,
      y1: 9.0,
      x2: 10.0,
      y2: 25.0,
      thickness: 0.15,
      isOuter: false,
      wallHeight: 3.0,
      wallThickness3d: 0.15,
    },
    {
      id: "A-i-v2",
      x1: 14.0,
      y1: 9.0,
      x2: 14.0,
      y2: 25.0,
      thickness: 0.15,
      isOuter: false,
      wallHeight: 3.0,
      wallThickness3d: 0.15,
    },
    {
      id: "A-i-v3",
      x1: 18.0,
      y1: 9.0,
      x2: 18.0,
      y2: 25.0,
      thickness: 0.15,
      isOuter: false,
      wallHeight: 3.0,
      wallThickness3d: 0.15,
    },
    {
      id: "A-i-h1",
      x1: 3.0,
      y1: 15.0,
      x2: 22.0,
      y2: 15.0,
      thickness: 0.15,
      isOuter: false,
      wallHeight: 3.0,
      wallThickness3d: 0.15,
    },
    {
      id: "A-i-h2",
      x1: 3.0,
      y1: 20.0,
      x2: 22.0,
      y2: 20.0,
      thickness: 0.15,
      isOuter: false,
      wallHeight: 3.0,
      wallThickness3d: 0.15,
    },
    {
      id: "A-i-h3",
      x1: 10.0,
      y1: 12.0,
      x2: 14.0,
      y2: 12.0,
      thickness: 0.15,
      isOuter: false,
      wallHeight: 3.0,
      wallThickness3d: 0.15,
    },
  ],
  doors: [
    {
      id: "A-door-1",
      x: 11.2,
      y: 25.0,
      width: 1.6,
      height: 2.4,
      wallId: "A-ow-n",
      rotation: 180,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "A-door-2",
      x: 10.0,
      y: 22.2,
      width: 1.2,
      height: 2.2,
      wallId: "A-i-v1",
      rotation: 270,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "A-door-3",
      x: 14.0,
      y: 22.2,
      width: 1.0,
      height: 2.2,
      wallId: "A-i-v2",
      rotation: 90,
      type: "hinged",
      openDirection: "right",
      swingAngle: 90,
    },
    {
      id: "A-door-4",
      x: 12.0,
      y: 20.0,
      width: 1.2,
      height: 2.2,
      wallId: "A-i-h2",
      rotation: 0,
      type: "hinged",
      openDirection: "right",
      swingAngle: 90,
    },
    {
      id: "A-door-5",
      x: 10.0,
      y: 17.0,
      width: 1.8,
      height: 2.3,
      wallId: "A-i-v1",
      rotation: 270,
      type: "sliding",
      openDirection: "center",
      swingAngle: 0,
    },
    {
      id: "A-door-6",
      x: 14.0,
      y: 17.0,
      width: 1.8,
      height: 2.3,
      wallId: "A-i-v2",
      rotation: 90,
      type: "sliding",
      openDirection: "center",
      swingAngle: 0,
    },
    {
      id: "A-door-7",
      x: 18.0,
      y: 17.0,
      width: 1.0,
      height: 2.2,
      wallId: "A-i-v3",
      rotation: 90,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "A-door-8",
      x: 6.5,
      y: 15.0,
      width: 1.0,
      height: 2.2,
      wallId: "A-i-h1",
      rotation: 0,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "A-door-9",
      x: 10.0,
      y: 10.5,
      width: 0.9,
      height: 2.1,
      wallId: "A-i-v1",
      rotation: 270,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "A-door-10",
      x: 12.0,
      y: 15.0,
      width: 0.9,
      height: 2.1,
      wallId: "A-i-h1",
      rotation: 0,
      type: "hinged",
      openDirection: "right",
      swingAngle: 90,
    },
    {
      id: "A-door-11",
      x: 16.0,
      y: 15.0,
      width: 1.0,
      height: 2.2,
      wallId: "A-i-h1",
      rotation: 0,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "A-door-12",
      x: 20.0,
      y: 15.0,
      width: 1.0,
      height: 2.2,
      wallId: "A-i-h1",
      rotation: 0,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "A-door-13",
      x: 20.0,
      y: 20.0,
      width: 1.0,
      height: 2.2,
      wallId: "A-i-h2",
      rotation: 0,
      type: "hinged",
      openDirection: "right",
      swingAngle: 90,
    },
  ],
  windows: [
    {
      id: "A-win-1",
      x1: 4.0,
      y1: 25.0,
      x2: 7.0,
      y2: 25.0,
      height: 1.8,
      sillHeight: 0.6,
      wallId: "A-ow-n",
    },
    {
      id: "A-win-2",
      x1: 3.0,
      y1: 21.0,
      x2: 3.0,
      y2: 23.0,
      height: 1.4,
      sillHeight: 0.9,
      wallId: "A-ow-w",
    },
    {
      id: "A-win-3",
      x1: 11.0,
      y1: 25.0,
      x2: 12.6,
      y2: 25.0,
      height: 1.6,
      sillHeight: 0.9,
      wallId: "A-ow-n",
    },
    {
      id: "A-win-4",
      x1: 14.8,
      y1: 25.0,
      x2: 17.0,
      y2: 25.0,
      height: 1.8,
      sillHeight: 0.8,
      wallId: "A-ow-n",
    },
    {
      id: "A-win-5",
      x1: 19.0,
      y1: 25.0,
      x2: 20.5,
      y2: 25.0,
      height: 1.2,
      sillHeight: 1.1,
      wallId: "A-ow-n",
    },
    {
      id: "A-win-6",
      x1: 3.0,
      y1: 16.2,
      x2: 3.0,
      y2: 18.2,
      height: 1.4,
      sillHeight: 0.9,
      wallId: "A-ow-w",
    },
    {
      id: "A-win-7",
      x1: 22.0,
      y1: 16.0,
      x2: 22.0,
      y2: 18.0,
      height: 1.2,
      sillHeight: 1.0,
      wallId: "A-ow-e",
    },
    {
      id: "A-win-8",
      x1: 5.0,
      y1: 9.0,
      x2: 8.0,
      y2: 9.0,
      height: 1.5,
      sillHeight: 0.8,
      wallId: "A-ow-s",
    },
    {
      id: "A-win-9",
      x1: 3.0,
      y1: 10.5,
      x2: 3.0,
      y2: 12.2,
      height: 1.2,
      sillHeight: 1.0,
      wallId: "A-ow-w",
    },
    {
      id: "A-win-10",
      x1: 15.0,
      y1: 9.0,
      x2: 17.0,
      y2: 9.0,
      height: 1.5,
      sillHeight: 0.8,
      wallId: "A-ow-s",
    },
    {
      id: "A-win-11",
      x1: 22.0,
      y1: 10.5,
      x2: 22.0,
      y2: 12.5,
      height: 1.2,
      sillHeight: 1.0,
      wallId: "A-ow-e",
    },
  ],
  stairs: [
    {
      id: "A-stairs-1",
      x: 19.9,
      y: 20.5,
      width: 1.5,
      height: 4.0,
      direction: "up",
    },
  ],
  // verticalTransport: [
  //   {
  //     id: "A-elevator-1",
  //     type: "elevator",
  //     x: 18.3,
  //     y: 22.2,
  //     width: 1.8,
  //     height: 1.8,
  //   },
  // ],
  furniture: [],
  // areaCalc: {
  //   plotArea: 750.0,
  //   buildableEnvelopeArea: 462.0,
  //   actualSetbacks: {
  //     front: 5.0,
  //     rear: 9.0,
  //     westSide: 3.0,
  //     eastSide: 3.0,
  //   },
  //   footprintArea: 304.0,
  //   openCourtyardArea: 20.0,
  //   enclosedFloorArea: 284.0,
  //   siteCoverage: 0.4053,
  //   farUsed: 0.3787,
  //   estimatedCost: 426000.0,
  //   budgetRemaining: 324000.0,
  //   roomAreas: {
  //     "Majlis (Living Room)": 35.0,
  //     "Guest Reception Lobby": 20.0,
  //     "Prayer Room": 20.0,
  //     "Core / Security / Elevator Lobby": 20.0,
  //     "Family Living": 35.0,
  //     Courtyard: 20.0,
  //     Dining: 20.0,
  //     Kitchen: 20.0,
  //     "Bedroom 1 (Master)": 42.0,
  //     "Bathroom 1": 12.0,
  //     "Bathroom 2": 12.0,
  //     "Bedroom 2": 24.0,
  //     "Bedroom 3": 24.0,
  //   },
  // },
  // designRationale: [
  //   "Central open-to-sky courtyard improves natural ventilation and daylight while preserving high privacy.",
  //   "North-facing entrance and larger north glazing reduce solar gain relative to east-west exposure in Riyadh.",
  //   "Guest zone is placed at the front, while bedrooms are pushed south for privacy and acoustic separation.",
  //   "Compact RC structural grid and 284 sqm enclosed area keep the scheme comfortably within the 750000 budget at 1500 per sqm.",
  //   "Window sizes are controlled to stay near the 20% window-wall ratio target, with smaller west/east openings and shaded north openings.",
  //   "Straight stair and elevator are grouped in one service core for accessibility, maintenance access, and future flexibility.",
  // ],
};
