import type { CanvasState } from "@/hooks/useDesignCanvasState";
// import { DEFAULT_META } from "@/hooks/useDesignCanvasState";

// export const DEMO_FLOOR_PLAN: CanvasState = {
// export const DEMO_FLOOR_PLAN: CanvasState = {
//   meta: {
//     version: 1,
//     unit: "m",
//     defaultWallHeight: 3,
//     defaultWallThickness: 0.25,
//     defaultInnerWallThickness: 0.15,
//     slabThickness: 0.2,
//     floorLevel: 0,
//     projectName: "Villa — Variant A Courtyard Spine",
//   },
//   rooms: [
//     {
//       id: "majlis",
//       label: "Majlis (Living Room)",
//       x: 3.5,
//       y: 20,
//       width: 6,
//       height: 5,
//       floor: {
//         color: "#e4d7c5",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "foyer",
//       label: "Entry Foyer",
//       x: 9.5,
//       y: 22,
//       width: 3,
//       height: 3,
//       floor: {
//         color: "#efe8dc",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "prayer",
//       label: "Prayer Room",
//       x: 3.5,
//       y: 17,
//       width: 3,
//       height: 3,
//       floor: {
//         color: "#d9cbb3",
//         material: "carpet",
//       },
//     },
//     {
//       id: "bathroom1",
//       label: "Bathroom 1",
//       x: 6.5,
//       y: 17,
//       width: 3,
//       height: 2.5,
//       floor: {
//         color: "#d7dde2",
//         material: "ceramic",
//       },
//     },
//     {
//       id: "stairs1",
//       label: "Straight Stair",
//       x: 9.5,
//       y: 17,
//       width: 3,
//       height: 5,
//       floor: {
//         color: "#d8d8d8",
//         material: "stone",
//       },
//     },
//     {
//       id: "elevator1",
//       label: "Elevator",
//       x: 12.8,
//       y: 20,
//       width: 2,
//       height: 2,
//       floor: {
//         color: "#cccccc",
//         material: "tile",
//       },
//     },
//     {
//       id: "courtyard",
//       label: "Courtyard",
//       x: 10,
//       y: 13.5,
//       width: 4,
//       height: 4,
//       floor: {
//         color: "#cbbf9d",
//         material: "stone",
//       },
//     },
//     {
//       id: "family_living_dining",
//       label: "Family Living + Dining",
//       x: 14,
//       y: 15,
//       width: 7.5,
//       height: 7,
//       floor: {
//         color: "#eadfcb",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "kitchen",
//       label: "Kitchen",
//       x: 17,
//       y: 10.5,
//       width: 4.5,
//       height: 4.5,
//       floor: {
//         color: "#f0f0f0",
//         material: "anti-slip tile",
//       },
//     },
//     {
//       id: "maids_room",
//       label: "Maid's Room",
//       x: 14,
//       y: 10.5,
//       width: 3,
//       height: 3,
//       floor: {
//         color: "#e6e1d6",
//         material: "vinyl",
//       },
//     },
//     {
//       id: "storage",
//       label: "Storage",
//       x: 14,
//       y: 8.5,
//       width: 2,
//       height: 2,
//       floor: {
//         color: "#dcdcdc",
//         material: "tile",
//       },
//     },
//     {
//       id: "bedroom1",
//       label: "Bedroom 1",
//       x: 3.5,
//       y: 11.5,
//       width: 4.5,
//       height: 5,
//       floor: {
//         color: "#e8d5b7",
//         material: "wood-look tile",
//       },
//     },
//     {
//       id: "bedroom2",
//       label: "Bedroom 2",
//       x: 8.5,
//       y: 8.5,
//       width: 4.5,
//       height: 4.5,
//       floor: {
//         color: "#e8d5b7",
//         material: "wood-look tile",
//       },
//     },
//     {
//       id: "master_bedroom",
//       label: "Bedroom 3 (Master)",
//       x: 3.5,
//       y: 6,
//       width: 5.5,
//       height: 4.5,
//       floor: {
//         color: "#e6d0b0",
//         material: "wood-look tile",
//       },
//     },
//     {
//       id: "bathroom2",
//       label: "Bathroom 2",
//       x: 16,
//       y: 8.5,
//       width: 3,
//       height: 2.5,
//       floor: {
//         color: "#d7dde2",
//         material: "ceramic",
//       },
//     },
//     {
//       id: "hall",
//       label: "Hall / Corridor",
//       x: 9,
//       y: 6,
//       width: 5,
//       height: 7.5,
//       floor: {
//         color: "#ece6db",
//         material: "porcelain",
//       },
//     },
//   ],
//   walls: [
//     {
//       id: "ow-n",
//       x1: 3.5,
//       y1: 25,
//       x2: 21.5,
//       y2: 25,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-e",
//       x1: 21.5,
//       y1: 6,
//       x2: 21.5,
//       y2: 25,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-s",
//       x1: 3.5,
//       y1: 6,
//       x2: 21.5,
//       y2: 6,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-w",
//       x1: 3.5,
//       y1: 6,
//       x2: 3.5,
//       y2: 25,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "iw-1",
//       x1: 9.5,
//       y1: 17,
//       x2: 9.5,
//       y2: 25,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "iw-2",
//       x1: 14,
//       y1: 8.5,
//       x2: 14,
//       y2: 22,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "iw-3",
//       x1: 3.5,
//       y1: 17,
//       x2: 14,
//       y2: 17,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "iw-4",
//       x1: 14,
//       y1: 15,
//       x2: 21.5,
//       y2: 15,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3,
//       wallThickness3d: 0.15,
//     },
//   ],
//   doors: [
//     {
//       id: "door-main",
//       x: 11,
//       y: 25,
//       width: 1.6,
//       height: 2.4,
//       wallId: "ow-n",
//       rotation: 180,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 100,
//     },
//     {
//       id: "door-majlis",
//       x: 9.5,
//       y: 22,
//       width: 1.2,
//       height: 2.2,
//       wallId: "iw-1",
//       rotation: 90,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//     {
//       id: "door-family",
//       x: 14,
//       y: 18,
//       width: 1.5,
//       height: 2.4,
//       wallId: "iw-2",
//       rotation: 90,
//       type: "sliding",
//       openDirection: "left",
//       swingAngle: 0,
//     },
//     {
//       id: "door-kitchen",
//       x: 18,
//       y: 15,
//       width: 1,
//       height: 2.2,
//       wallId: "iw-4",
//       rotation: 180,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "door-bed1",
//       x: 8,
//       y: 13,
//       width: 0.95,
//       height: 2.2,
//       wallId: "iw-3",
//       rotation: 180,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//   ],
//   windows: [
//     {
//       id: "win-majlis-n",
//       x1: 4.2,
//       y1: 25,
//       x2: 7.2,
//       y2: 25,
//       height: 1.5,
//       sillHeight: 0.9,
//       wallId: "ow-n",
//     },
//     {
//       id: "win-foyer-n",
//       x1: 10.2,
//       y1: 25,
//       x2: 11.8,
//       y2: 25,
//       height: 1.5,
//       sillHeight: 1.1,
//       wallId: "ow-n",
//     },
//     {
//       id: "win-family-e",
//       x1: 21.5,
//       y1: 16.2,
//       x2: 21.5,
//       y2: 19.8,
//       height: 1.6,
//       sillHeight: 0.8,
//       wallId: "ow-e",
//     },
//     {
//       id: "win-kitchen-e",
//       x1: 21.5,
//       y1: 11.5,
//       x2: 21.5,
//       y2: 13.5,
//       height: 1.2,
//       sillHeight: 1.2,
//       wallId: "ow-e",
//     },
//     {
//       id: "win-bed1-w",
//       x1: 3.5,
//       y1: 12.5,
//       x2: 3.5,
//       y2: 14.5,
//       height: 1.4,
//       sillHeight: 1,
//       wallId: "ow-w",
//     },
//     {
//       id: "win-master-s",
//       x1: 5,
//       y1: 6,
//       x2: 7.2,
//       y2: 6,
//       height: 1.4,
//       sillHeight: 1,
//       wallId: "ow-s",
//     },
//   ],
//   stairs: [
//     {
//       id: "stairs-1",
//       x: 9.5,
//       y: 17,
//       width: 3,
//       height: 5,
//       direction: "up",
//     },
//   ],
//   furniture: [],
//   // areaCalc: {
//   //   plotArea: 750,
//   //   buildableEnvelopeArea: 462,
//   //   footprintArea: 342,
//   //   openCourtyardArea: 16,
//   //   enclosedBuiltArea: 326,
//   //   estimatedCirculationAndWallArea: 106.75,
//   //   roomAreas: {
//   //     majlis: 30,
//   //     foyer: 9,
//   //     prayer: 9,
//   //     bathroom1: 7.5,
//   //     family_living_dining: 52.5,
//   //     kitchen: 20.25,
//   //     maids_room: 9,
//   //     storage: 4,
//   //     bedroom1: 22.5,
//   //     bedroom2: 20.25,
//   //     master_bedroom: 24.75,
//   //     bathroom2: 7.5,
//   //     hall: 37.5,
//   //     stairs: 15,
//   //     elevator: 4,
//   //     courtyard: 16,
//   //   },
//   //   parkingAreaReserved: 30,
//   //   estimatedConstructionCost: 489000,
//   //   budgetCheck: {
//   //     withinBudget: true,
//   //     budget: 750000,
//   //     estimatedCost: 489000,
//   //     remainingAllowance: 261000,
//   //   },
//   // },
//   // designRationale:
//   //   "Variant A uses a central courtyard spine to bring daylight into the middle of the house while preserving high privacy. Public functions are placed to the north for formal access, with the Majlis and guest reception near the main entrance. Family living, dining, and kitchen are grouped to the east and southeast in an open-plan arrangement. Bedrooms are pushed to the south and southwest for privacy. Windows are limited on exposed hot facades and are larger on north and east sides to support daylight and natural ventilation from prevailing NW winds. RC structure, insulated wall assembly, R13 insulation, central AC, elevator, and straight stair are included.",
// };

// export const DEMO_FLOOR_PLAN: CanvasState = {
//   meta: {
//     version: 1,
//     unit: "m",
//     defaultWallHeight: 3.0,
//     defaultWallThickness: 0.25,
//     defaultInnerWallThickness: 0.15,
//     slabThickness: 0.18,
//     floorLevel: 0.0,
//     projectName: "Villa — Variant A — Central Courtyard",
//   },
//   rooms: [
//     {
//       id: "A-majlis",
//       label: "Majlis (Living Room)",
//       x: 3.0,
//       y: 20.0,
//       width: 7.0,
//       height: 5.0,
//       // area: 35.0,
//       floor: {
//         color: "#d9d4c7",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "A-guest-lobby",
//       label: "Guest Reception Lobby",
//       x: 10.0,
//       y: 20.0,
//       width: 4.0,
//       height: 5.0,
//       // area: 20.0,
//       floor: {
//         color: "#e7e2d8",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "A-prayer",
//       label: "Prayer Room",
//       x: 14.0,
//       y: 20.0,
//       width: 4.0,
//       height: 5.0,
//       // area: 20.0,
//       floor: {
//         color: "#cbbf9d",
//         material: "carpet",
//       },
//     },
//     {
//       id: "A-core",
//       label: "Core / Security / Elevator Lobby",
//       x: 18.0,
//       y: 20.0,
//       width: 4.0,
//       height: 5.0,
//       // area: 20.0,
//       floor: {
//         color: "#dfe3e6",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "A-family",
//       label: "Family Living",
//       x: 3.0,
//       y: 15.0,
//       width: 7.0,
//       height: 5.0,
//       // area: 35.0,
//       floor: {
//         color: "#d8c8b2",
//         material: "wood-look porcelain",
//       },
//     },
//     {
//       id: "A-courtyard",
//       label: "Courtyard",
//       x: 10.0,
//       y: 15.0,
//       width: 4.0,
//       height: 5.0,
//       // area: 20.0,
//       // openToSky: true,
//       floor: {
//         color: "#c9b79c",
//         material: "stone",
//       },
//     },
//     {
//       id: "A-dining",
//       label: "Dining",
//       x: 14.0,
//       y: 15.0,
//       width: 4.0,
//       height: 5.0,
//       // area: 20.0,
//       floor: {
//         color: "#d8c8b2",
//         material: "wood-look porcelain",
//       },
//     },
//     {
//       id: "A-kitchen",
//       label: "Kitchen",
//       x: 18.0,
//       y: 15.0,
//       width: 4.0,
//       height: 5.0,
//       // area: 20.0,
//       floor: {
//         color: "#e2e2de",
//         material: "porcelain",
//       },
//     },
//     {
//       id: "A-master",
//       label: "Bedroom 1 (Master)",
//       x: 3.0,
//       y: 9.0,
//       width: 7.0,
//       height: 6.0,
//       // area: 42.0,
//       floor: {
//         color: "#cdb89d",
//         material: "wood-look porcelain",
//       },
//     },
//     {
//       id: "A-bath-1",
//       label: "Bathroom 1",
//       x: 10.0,
//       y: 9.0,
//       width: 4.0,
//       height: 3.0,
//       // area: 12.0,
//       floor: {
//         color: "#d8dde0",
//         material: "anti-slip porcelain",
//       },
//     },
//     {
//       id: "A-bath-2",
//       label: "Bathroom 2",
//       x: 10.0,
//       y: 12.0,
//       width: 4.0,
//       height: 3.0,
//       // area: 12.0,
//       floor: {
//         color: "#d8dde0",
//         material: "anti-slip porcelain",
//       },
//     },
//     {
//       id: "A-bed-2",
//       label: "Bedroom 2",
//       x: 14.0,
//       y: 9.0,
//       width: 4.0,
//       height: 6.0,
//       // area: 24.0,
//       floor: {
//         color: "#cfbea8",
//         material: "wood-look porcelain",
//       },
//     },
//     {
//       id: "A-bed-3",
//       label: "Bedroom 3",
//       x: 18.0,
//       y: 9.0,
//       width: 4.0,
//       height: 6.0,
//       // area: 24.0,
//       floor: {
//         color: "#cfbea8",
//         material: "wood-look porcelain",
//       },
//     },
//   ],
//   walls: [
//     {
//       id: "A-ow-s",
//       x1: 3.0,
//       y1: 9.0,
//       x2: 22.0,
//       y2: 9.0,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.0,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "A-ow-e",
//       x1: 22.0,
//       y1: 9.0,
//       x2: 22.0,
//       y2: 25.0,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.0,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "A-ow-n",
//       x1: 22.0,
//       y1: 25.0,
//       x2: 3.0,
//       y2: 25.0,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.0,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "A-ow-w",
//       x1: 3.0,
//       y1: 25.0,
//       x2: 3.0,
//       y2: 9.0,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.0,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "A-i-v1",
//       x1: 10.0,
//       y1: 9.0,
//       x2: 10.0,
//       y2: 25.0,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3.0,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "A-i-v2",
//       x1: 14.0,
//       y1: 9.0,
//       x2: 14.0,
//       y2: 25.0,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3.0,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "A-i-v3",
//       x1: 18.0,
//       y1: 9.0,
//       x2: 18.0,
//       y2: 25.0,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3.0,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "A-i-h1",
//       x1: 3.0,
//       y1: 15.0,
//       x2: 22.0,
//       y2: 15.0,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3.0,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "A-i-h2",
//       x1: 3.0,
//       y1: 20.0,
//       x2: 22.0,
//       y2: 20.0,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3.0,
//       wallThickness3d: 0.15,
//     },
//     {
//       id: "A-i-h3",
//       x1: 10.0,
//       y1: 12.0,
//       x2: 14.0,
//       y2: 12.0,
//       thickness: 0.15,
//       isOuter: false,
//       wallHeight: 3.0,
//       wallThickness3d: 0.15,
//     },
//   ],
//   doors: [
//     {
//       id: "A-door-1",
//       x: 11.2,
//       y: 25.0,
//       width: 1.6,
//       height: 2.4,
//       wallId: "A-ow-n",
//       rotation: 180,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-2",
//       x: 10.0,
//       y: 22.2,
//       width: 1.2,
//       height: 2.2,
//       wallId: "A-i-v1",
//       rotation: 270,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-3",
//       x: 14.0,
//       y: 22.2,
//       width: 1.0,
//       height: 2.2,
//       wallId: "A-i-v2",
//       rotation: 90,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-4",
//       x: 12.0,
//       y: 20.0,
//       width: 1.2,
//       height: 2.2,
//       wallId: "A-i-h2",
//       rotation: 0,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-5",
//       x: 10.0,
//       y: 17.0,
//       width: 1.8,
//       height: 2.3,
//       wallId: "A-i-v1",
//       rotation: 270,
//       type: "sliding",
//       openDirection: "center",
//       swingAngle: 0,
//     },
//     {
//       id: "A-door-6",
//       x: 14.0,
//       y: 17.0,
//       width: 1.8,
//       height: 2.3,
//       wallId: "A-i-v2",
//       rotation: 90,
//       type: "sliding",
//       openDirection: "center",
//       swingAngle: 0,
//     },
//     {
//       id: "A-door-7",
//       x: 18.0,
//       y: 17.0,
//       width: 1.0,
//       height: 2.2,
//       wallId: "A-i-v3",
//       rotation: 90,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-8",
//       x: 6.5,
//       y: 15.0,
//       width: 1.0,
//       height: 2.2,
//       wallId: "A-i-h1",
//       rotation: 0,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-9",
//       x: 10.0,
//       y: 10.5,
//       width: 0.9,
//       height: 2.1,
//       wallId: "A-i-v1",
//       rotation: 270,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-10",
//       x: 12.0,
//       y: 15.0,
//       width: 0.9,
//       height: 2.1,
//       wallId: "A-i-h1",
//       rotation: 0,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-11",
//       x: 16.0,
//       y: 15.0,
//       width: 1.0,
//       height: 2.2,
//       wallId: "A-i-h1",
//       rotation: 0,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-12",
//       x: 20.0,
//       y: 15.0,
//       width: 1.0,
//       height: 2.2,
//       wallId: "A-i-h1",
//       rotation: 0,
//       type: "hinged",
//       openDirection: "left",
//       swingAngle: 90,
//     },
//     {
//       id: "A-door-13",
//       x: 20.0,
//       y: 20.0,
//       width: 1.0,
//       height: 2.2,
//       wallId: "A-i-h2",
//       rotation: 0,
//       type: "hinged",
//       openDirection: "right",
//       swingAngle: 90,
//     },
//   ],
//   windows: [
//     {
//       id: "A-win-1",
//       x1: 4.0,
//       y1: 25.0,
//       x2: 7.0,
//       y2: 25.0,
//       height: 1.8,
//       sillHeight: 0.6,
//       wallId: "A-ow-n",
//     },
//     {
//       id: "A-win-2",
//       x1: 3.0,
//       y1: 21.0,
//       x2: 3.0,
//       y2: 23.0,
//       height: 1.4,
//       sillHeight: 0.9,
//       wallId: "A-ow-w",
//     },
//     {
//       id: "A-win-3",
//       x1: 11.0,
//       y1: 25.0,
//       x2: 12.6,
//       y2: 25.0,
//       height: 1.6,
//       sillHeight: 0.9,
//       wallId: "A-ow-n",
//     },
//     {
//       id: "A-win-4",
//       x1: 14.8,
//       y1: 25.0,
//       x2: 17.0,
//       y2: 25.0,
//       height: 1.8,
//       sillHeight: 0.8,
//       wallId: "A-ow-n",
//     },
//     {
//       id: "A-win-5",
//       x1: 19.0,
//       y1: 25.0,
//       x2: 20.5,
//       y2: 25.0,
//       height: 1.2,
//       sillHeight: 1.1,
//       wallId: "A-ow-n",
//     },
//     {
//       id: "A-win-6",
//       x1: 3.0,
//       y1: 16.2,
//       x2: 3.0,
//       y2: 18.2,
//       height: 1.4,
//       sillHeight: 0.9,
//       wallId: "A-ow-w",
//     },
//     {
//       id: "A-win-7",
//       x1: 22.0,
//       y1: 16.0,
//       x2: 22.0,
//       y2: 18.0,
//       height: 1.2,
//       sillHeight: 1.0,
//       wallId: "A-ow-e",
//     },
//     {
//       id: "A-win-8",
//       x1: 5.0,
//       y1: 9.0,
//       x2: 8.0,
//       y2: 9.0,
//       height: 1.5,
//       sillHeight: 0.8,
//       wallId: "A-ow-s",
//     },
//     {
//       id: "A-win-9",
//       x1: 3.0,
//       y1: 10.5,
//       x2: 3.0,
//       y2: 12.2,
//       height: 1.2,
//       sillHeight: 1.0,
//       wallId: "A-ow-w",
//     },
//     {
//       id: "A-win-10",
//       x1: 15.0,
//       y1: 9.0,
//       x2: 17.0,
//       y2: 9.0,
//       height: 1.5,
//       sillHeight: 0.8,
//       wallId: "A-ow-s",
//     },
//     {
//       id: "A-win-11",
//       x1: 22.0,
//       y1: 10.5,
//       x2: 22.0,
//       y2: 12.5,
//       height: 1.2,
//       sillHeight: 1.0,
//       wallId: "A-ow-e",
//     },
//   ],
//   stairs: [
//     {
//       id: "A-stairs-1",
//       x: 19.9,
//       y: 20.5,
//       width: 1.5,
//       height: 4.0,
//       direction: "up",
//     },
//   ],
//   // verticalTransport: [
//   //   {
//   //     id: "A-elevator-1",
//   //     type: "elevator",
//   //     x: 18.3,
//   //     y: 22.2,
//   //     width: 1.8,
//   //     height: 1.8,
//   //   },
//   // ],
//   furniture: [],
//   // areaCalc: {
//   //   plotArea: 750.0,
//   //   buildableEnvelopeArea: 462.0,
//   //   actualSetbacks: {
//   //     front: 5.0,
//   //     rear: 9.0,
//   //     westSide: 3.0,
//   //     eastSide: 3.0,
//   //   },
//   //   footprintArea: 304.0,
//   //   openCourtyardArea: 20.0,
//   //   enclosedFloorArea: 284.0,
//   //   siteCoverage: 0.4053,
//   //   farUsed: 0.3787,
//   //   estimatedCost: 426000.0,
//   //   budgetRemaining: 324000.0,
//   //   roomAreas: {
//   //     "Majlis (Living Room)": 35.0,
//   //     "Guest Reception Lobby": 20.0,
//   //     "Prayer Room": 20.0,
//   //     "Core / Security / Elevator Lobby": 20.0,
//   //     "Family Living": 35.0,
//   //     Courtyard: 20.0,
//   //     Dining: 20.0,
//   //     Kitchen: 20.0,
//   //     "Bedroom 1 (Master)": 42.0,
//   //     "Bathroom 1": 12.0,
//   //     "Bathroom 2": 12.0,
//   //     "Bedroom 2": 24.0,
//   //     "Bedroom 3": 24.0,
//   //   },
//   // },
//   // designRationale: [
//   //   "Central open-to-sky courtyard improves natural ventilation and daylight while preserving high privacy.",
//   //   "North-facing entrance and larger north glazing reduce solar gain relative to east-west exposure in Riyadh.",
//   //   "Guest zone is placed at the front, while bedrooms are pushed south for privacy and acoustic separation.",
//   //   "Compact RC structural grid and 284 sqm enclosed area keep the scheme comfortably within the 750000 budget at 1500 per sqm.",
//   //   "Window sizes are controlled to stay near the 20% window-wall ratio target, with smaller west/east openings and shaded north openings.",
//   //   "Straight stair and elevator are grouped in one service core for accessibility, maintenance access, and future flexibility.",
//   // ],
// };

// export const DEMO_FLOOR_PLAN: CanvasState = {
//   meta: {
//     version: 1,
//     unit: "m",
//     defaultWallHeight: 3.2,
//     defaultWallThickness: 0.25,
//     defaultInnerWallThickness: 0.15,
//     slabThickness: 0.2,
//     floorLevel: 0,
//     projectName: "Villa — Variant A",
//   },
//   rooms: [
//     {
//       id: "vA-majlis",
//       label: "Majlis (Living Room)",
//       x: 0,
//       y: 0,
//       width: 6.2,
//       height: 7.2,
//       floor: {
//         color: "#e8e2d6",
//         material: "stone",
//       },
//     },
//     {
//       id: "vA-bedroom1",
//       label: "Bedroom 1",
//       x: 6.2,
//       y: 0,
//       width: 4.47,
//       height: 3.6,
//       floor: {
//         color: "#e9dfd2",
//         material: "wood",
//       },
//     },
//     {
//       id: "vA-bedroom2",
//       label: "Bedroom 2",
//       x: 6.2,
//       y: 3.6,
//       width: 4.47,
//       height: 3.6,
//       floor: {
//         color: "#e9dfd2",
//         material: "wood",
//       },
//     },
//     {
//       id: "vA-bedroom3",
//       label: "Bedroom 3",
//       x: 0,
//       y: 7.2,
//       width: 3.56,
//       height: 6.3,
//       floor: {
//         color: "#e9dfd2",
//         material: "wood",
//       },
//     },
//     {
//       id: "vA-bathroom1",
//       label: "Bathroom 1",
//       x: 3.56,
//       y: 7.2,
//       width: 3.55,
//       height: 3.15,
//       floor: {
//         color: "#dfe7ea",
//         material: "tile",
//       },
//     },
//     {
//       id: "vA-bedroom4",
//       label: "Bedroom 4",
//       x: 3.56,
//       y: 10.35,
//       width: 3.55,
//       height: 3.15,
//       floor: {
//         color: "#e9dfd2",
//         material: "wood",
//       },
//     },
//     {
//       id: "vA-bedroom5",
//       label: "Bedroom 5",
//       x: 7.11,
//       y: 7.2,
//       width: 3.56,
//       height: 6.3,
//       floor: {
//         color: "#e9dfd2",
//         material: "wood",
//       },
//     },
//     {
//       id: "vA-bathroom2",
//       label: "Bathroom 2",
//       x: 0,
//       y: 13.5,
//       width: 10.67,
//       height: 6.31,
//       floor: {
//         color: "#dfe7ea",
//         material: "tile",
//       },
//     },
//   ],
//   walls: [
//     {
//       id: "ow-n",
//       x1: 0,
//       y1: 0,
//       x2: 10.67,
//       y2: 0,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.2,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-e",
//       x1: 10.67,
//       y1: 0,
//       x2: 10.67,
//       y2: 19.81,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.2,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-s",
//       x1: 10.67,
//       y1: 19.81,
//       x2: 0,
//       y2: 19.81,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.2,
//       wallThickness3d: 0.25,
//     },
//     {
//       id: "ow-w",
//       x1: 0,
//       y1: 19.81,
//       x2: 0,
//       y2: 0,
//       thickness: 0.25,
//       isOuter: true,
//       wallHeight: 3.2,
//       wallThickness3d: 0.25,
//     },
//   ],
//   doors: [
//     {
//       id: "vA-door-entrance",
//       x: 2.5,
//       y: 0,
//       width: 1.2,
//       height: 2.2,
//       wallId: "ow-n",
//       rotation: 0,
//       type: "hinged",
//       openDirection: "in",
//       swingAngle: 90,
//     },
//   ],
//   windows: [
//     {
//       id: "vA-win-majlis-n",
//       x1: 0.8,
//       y1: 0,
//       x2: 2.8,
//       y2: 0,
//       height: 1.4,
//       sillHeight: 0.9,
//       wallId: "ow-n",
//     },
//     {
//       id: "vA-win-bed1-n",
//       x1: 7.2,
//       y1: 0,
//       x2: 9.0,
//       y2: 0,
//       height: 1.4,
//       sillHeight: 0.9,
//       wallId: "ow-n",
//     },
//     {
//       id: "vA-win-bath2-s",
//       x1: 4.0,
//       y1: 19.81,
//       x2: 6.0,
//       y2: 19.81,
//       height: 0.8,
//       sillHeight: 1.6,
//       wallId: "ow-s",
//     },
//   ],
//   stairs: [],
//   furniture: [],
// };

/* Previously active demo — "1-Bedroom House with Majlis" (commented; restore by swapping with export below).
export const DEMO_FLOOR_PLAN: CanvasState = {
  meta: {
    version: 1,
    unit: "m",
    defaultWallHeight: 3.0,
    defaultWallThickness: 0.3,
    defaultInnerWallThickness: 0.2,
    slabThickness: 0.25,
    floorLevel: 0,
    projectName: "1-Bedroom House with Majlis",
  },
  rooms: [
    {
      id: "majlis",
      label: "Majlis (Living Room)",
      x: 0,
      y: 0,
      width: 4.57,
      height: 4.88,
      floor: {
        color: "#E8D5B7",
        material: "tile",
      },
    },
    {
      id: "bedroom",
      label: "Bedroom",
      x: 4.57,
      y: 0,
      width: 3.96,
      height: 4.57,
      floor: {
        color: "#E8D5B7",
        material: "tile",
      },
    },
    {
      id: "bath1",
      label: "Bath 1",
      x: 0,
      y: 4.88,
      width: 2.13,
      height: 1.83,
      floor: {
        color: "#E8D5B7",
        material: "tile",
      },
    },
    {
      id: "bath2",
      label: "Bath 2",
      x: 2.13,
      y: 4.88,
      width: 2.13,
      height: 1.52,
      floor: {
        color: "#E8D5B7",
        material: "tile",
      },
    },
    {
      id: "store",
      label: "Store",
      x: 0,
      y: 6.71,
      width: 1.83,
      height: 1.52,
      floor: {
        color: "#E8D5B7",
        material: "tile",
      },
    },
    {
      id: "stairs",
      label: "Stairs",
      x: 5.49,
      y: 2.44,
      width: 1.83,
      height: 2.13,
      floor: {
        color: "#E8D5B7",
        material: "tile",
      },
    },
  ],
  walls: [
    {
      id: "wall-1",
      x1: 0,
      y1: 0,
      x2: 4.57,
      y2: 0,
      thickness: 0.3,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.3,
    },
    {
      id: "wall-2",
      x1: 0,
      y1: 0,
      x2: 0,
      y2: 4.88,
      thickness: 0.3,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.3,
    },
    {
      id: "wall-3",
      x1: 4.57,
      y1: 0,
      x2: 4.57,
      y2: 4.88,
      thickness: 0.3,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.3,
    },
    {
      id: "wall-4",
      x1: 0,
      y1: 4.88,
      x2: 4.57,
      y2: 4.88,
      thickness: 0.3,
      isOuter: true,
      wallHeight: 3.0,
      wallThickness3d: 0.3,
    },
  ],
  doors: [
    {
      id: "door-1",
      x: 2.13,
      y: 0,
      width: 1.0,
      height: 2.0,
      wallId: "wall-1",
      rotation: 0,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
    {
      id: "door-2",
      x: 4.57,
      y: 2.44,
      width: 1.0,
      height: 2.0,
      wallId: "wall-3",
      rotation: 0,
      type: "hinged",
      openDirection: "left",
      swingAngle: 90,
    },
  ],
  windows: [],
  stairs: [
    {
      id: "stairs-1",
      x: 5.49,
      y: 2.44,
      width: 1.83,
      height: 2.13,
    },
  ],
  furniture: [],
};
*/

/** Unit C1 — 3-Bedroom apartment (based on reference floor-plan image).
 *  Imperial dims converted to metres. Overall envelope ≈ 14.5 m × 8.9 m. */
// export const DEMO_FLOOR_PLAN: CanvasState = {
//   meta: {
//     version: 1,
//     unit: "m",
//     defaultWallHeight: 2.9,
//     defaultWallThickness: 0.25,
//     defaultInnerWallThickness: 0.12,
//     slabThickness: 0.18,
//     floorLevel: 0,
//     projectName: "Unit C1 — 3 Bed Apartment",
//   },

//   /* ------------------------------------------------------------------ */
//   /*  ROOMS                                                             */
//   /* ------------------------------------------------------------------ */
//   rooms: [
//     /* ---- top row ---- */
//     { id: "bed1", label: "Bedroom", x: 0, y: 0, width: 3.65, height: 3.02, floor: { color: "#f5f0e8", material: "wood" } },
//     { id: "bed2", label: "Bedroom", x: 3.65, y: 0, width: 3.82, height: 3.51, floor: { color: "#f5f0e8", material: "wood" } },
//     { id: "balcony", label: "Balcony", x: 7.0, y: 0, width: 2.5, height: 1.83, floor: { color: "#d7d2c7", material: "stone" } },
//     { id: "kitchen", label: "Kitchen", x: 7.0, y: 1.83, width: 2.85, height: 2.21, floor: { color: "#ece8df", material: "tile" } },
//     { id: "living", label: "Living", x: 9.5, y: 0, width: 5.0, height: 5.31, floor: { color: "#f0e8d8", material: "wood" } },

//     /* ---- middle / closet band ---- */
//     { id: "wic1", label: "Walk-in Closet", x: 0, y: 3.02, width: 1.55, height: 1.52, floor: { color: "#efe7da", material: "vinyl" } },
//     { id: "closet1", label: "Closet", x: 1.6, y: 3.5, width: 1.0, height: 1.3, floor: { color: "#efe7da", material: "vinyl" } },
//     { id: "wic2", label: "Walk-in Closet", x: 4.85, y: 3.51, width: 2.08, height: 1.6, floor: { color: "#efe7da", material: "vinyl" } },

//     /* ---- corridor / services band ---- */
//     { id: "hall", label: "Hall", x: 3.65, y: 5.2, width: 3.35, height: 1.9, floor: { color: "#e6ded1", material: "tile" } },
//     { id: "laundry", label: "Laundry", x: 3.65, y: 7.1, width: 1.5, height: 1.0, floor: { color: "#e2e2e2", material: "tile" } },
//     { id: "closet2", label: "Closet", x: 7.0, y: 7.4, width: 1.1, height: 1.0, floor: { color: "#efe7da", material: "vinyl" } },
//     { id: "mech", label: "Mech", x: 7.5, y: 5.4, width: 1.05, height: 0.85, floor: { color: "#dddddd", material: "concrete" } },

//     /* ---- bottom row ---- */
//     { id: "bath1", label: "Bath", x: 0, y: 7.1, width: 3.65, height: 1.8, floor: { color: "#d4e6f1", material: "tile" } },
//     { id: "wic3", label: "Walk-in Closet", x: 8.55, y: 5.35, width: 1.6, height: 1.55, floor: { color: "#efe7da", material: "vinyl" } },
//     { id: "bath2", label: "Bath", x: 8.2, y: 6.9, width: 2.3, height: 1.78, floor: { color: "#d4e6f1", material: "tile" } },
//     { id: "bed3", label: "Bedroom", x: 10.85, y: 5.35, width: 3.65, height: 3.55, floor: { color: "#f5f0e8", material: "wood" } },
//   ],

//   /* ------------------------------------------------------------------ */
//   /*  WALLS                                                             */
//   /* ------------------------------------------------------------------ */
//   walls: [
//     /* outer perimeter */
//     { id: "ow-n", x1: 0, y1: 0, x2: 14.5, y2: 0, thickness: 10, isOuter: true, wallHeight: 2.9, wallThickness3d: 0.25 },
//     { id: "ow-e", x1: 14.5, y1: 0, x2: 14.5, y2: 8.9, thickness: 10, isOuter: true, wallHeight: 2.9, wallThickness3d: 0.25 },
//     { id: "ow-s", x1: 0, y1: 8.9, x2: 14.5, y2: 8.9, thickness: 10, isOuter: true, wallHeight: 2.9, wallThickness3d: 0.25 },
//     { id: "ow-w", x1: 0, y1: 0, x2: 0, y2: 8.9, thickness: 10, isOuter: true, wallHeight: 2.9, wallThickness3d: 0.25 },
//     /* inner partitions (hidden by filter; kept for door refs & export) */
//     { id: "iw-1", x1: 3.65, y1: 0, x2: 3.65, y2: 5.2, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//     { id: "iw-2", x1: 7.0, y1: 0, x2: 7.0, y2: 5.2, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//     { id: "iw-3", x1: 9.5, y1: 0, x2: 9.5, y2: 5.31, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//     { id: "iw-4", x1: 0, y1: 5.2, x2: 9.5, y2: 5.2, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//     { id: "iw-5", x1: 10.85, y1: 5.35, x2: 10.85, y2: 8.9, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//     { id: "iw-6", x1: 7.0, y1: 5.35, x2: 14.5, y2: 5.35, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//     { id: "iw-7", x1: 0, y1: 7.1, x2: 7.0, y2: 7.1, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//     { id: "iw-8", x1: 8.2, y1: 6.9, x2: 10.85, y2: 6.9, thickness: 8, isOuter: false, wallHeight: 2.9, wallThickness3d: 0.12 },
//   ],

//   /* ------------------------------------------------------------------ */
//   /*  DOORS                                                             */
//   /* ------------------------------------------------------------------ */
//   doors: [
//     { id: "d-bed1", x: 2.0, y: 5.18, width: 0.85, height: 2.05, wallId: "iw-4", rotation: 0, type: "hinged", label: "Bedroom" },
//     { id: "d-bed2", x: 5.5, y: 5.18, width: 0.85, height: 2.05, wallId: "iw-4", rotation: 0, type: "hinged", label: "Bedroom" },
//     { id: "d-kitchen", x: 9.48, y: 3.6, width: 0.9, height: 2.05, wallId: "iw-3", rotation: 90, type: "hinged", label: "Kitchen" },
//     { id: "d-bath1", x: 2.0, y: 7.08, width: 0.75, height: 2.0, wallId: "iw-7", rotation: 0, type: "hinged", label: "Bath" },
//     { id: "d-bath2", x: 9.6, y: 6.88, width: 0.75, height: 2.0, wallId: "iw-8", rotation: 0, type: "hinged", label: "Bath" },
//     { id: "d-bed3", x: 10.83, y: 7.2, width: 0.9, height: 2.05, wallId: "iw-5", rotation: 90, type: "hinged", label: "Bedroom" },
//     { id: "d-entry", x: 6.8, y: 8.88, width: 1.0, height: 2.1, wallId: "ow-s", rotation: 180, type: "hinged", label: "Main Entry" },
//     { id: "d-wic1", x: 0.6, y: 3.0, width: 0.7, height: 2.0, wallId: "iw-4", rotation: 180, type: "hinged", label: "Closet" },
//     { id: "d-wic2", x: 5.7, y: 3.49, width: 0.7, height: 2.0, wallId: "iw-1", rotation: 180, type: "hinged", label: "Closet" },
//     { id: "d-wic3", x: 9.35, y: 5.33, width: 0.7, height: 2.0, wallId: "iw-6", rotation: 0, type: "hinged", label: "Closet" },
//   ],

//   /* ------------------------------------------------------------------ */
//   /*  WINDOWS                                                           */
//   /* ------------------------------------------------------------------ */
//   windows: [
//     { id: "w-bed1-w", x1: 0, y1: 0.6, x2: 0, y2: 2.0, height: 1.2, sillHeight: 0.9, wallId: "ow-w" },
//     { id: "w-bed2-n", x1: 4.5, y1: 0, x2: 5.9, y2: 0, height: 1.2, sillHeight: 0.9, wallId: "ow-n" },
//     { id: "w-balcony", x1: 7.5, y1: 0, x2: 9.0, y2: 0, height: 2.1, sillHeight: 0, wallId: "ow-n" },
//     { id: "w-living-n", x1: 11.0, y1: 0, x2: 13.0, y2: 0, height: 1.35, sillHeight: 0.85, wallId: "ow-n" },
//     { id: "w-living-e", x1: 14.5, y1: 1.5, x2: 14.5, y2: 3.5, height: 1.35, sillHeight: 0.85, wallId: "ow-e" },
//     { id: "w-bed3-e", x1: 14.5, y1: 6.2, x2: 14.5, y2: 7.8, height: 1.2, sillHeight: 0.9, wallId: "ow-e" },
//   ],

//   /* ------------------------------------------------------------------ */
//   /*  STAIRS                                                            */
//   /* ------------------------------------------------------------------ */
//   stairs: [],

//   /* ------------------------------------------------------------------ */
//   /*  FURNITURE                                                         */
//   /* ------------------------------------------------------------------ */
//   furniture: [
//     /* living */
//     { id: "f-sofa", furnitureType: "sofa", label: "L-Sofa", x: 10.2, y: 1.8, width: 2.4, depth: 0.9, rotation: 90, height3d: 0.75, color3d: "#7a6a5a" },
//     { id: "f-coffee", furnitureType: "coffee-table", label: "Coffee Table", x: 11.6, y: 2.4, width: 0.9, depth: 0.5, rotation: 0, height3d: 0.45, color3d: "#8b7355" },
//     { id: "f-dining", furnitureType: "dining-table", label: "Dining Table", x: 12.6, y: 1.2, width: 1.1, depth: 0.7, rotation: 0, height3d: 0.75, color3d: "#a08060" },
//     /* kitchen */
//     { id: "f-counter", furnitureType: "counter", label: "Counter", x: 7.15, y: 1.95, width: 2.5, depth: 0.65, rotation: 0, height3d: 0.9, color3d: "#a08060" },
//     { id: "f-stove", furnitureType: "stove", label: "Stove", x: 8.3, y: 2.7, width: 0.6, depth: 0.6, rotation: 0, height3d: 0.9, color3d: "#c0c0c0" },
//     { id: "f-sink-k", furnitureType: "sink", label: "Kitchen Sink", x: 7.25, y: 2.7, width: 0.6, depth: 0.5, rotation: 0, height3d: 0.85, color3d: "#e8e8e8" },
//     /* bedroom 1 */
//     { id: "f-bed1", furnitureType: "bed-double", label: "Bed", x: 0.6, y: 0.45, width: 1.9, depth: 1.5, rotation: 0, height3d: 0.55, color3d: "#f5f0e8" },
//     /* bedroom 2 */
//     { id: "f-bed2", furnitureType: "bed-double", label: "Bed", x: 4.35, y: 0.5, width: 1.9, depth: 1.5, rotation: 0, height3d: 0.55, color3d: "#f5f0e8" },
//     /* bedroom 3 */
//     { id: "f-bed3", furnitureType: "bed-double", label: "Bed", x: 11.4, y: 6.05, width: 1.9, depth: 1.5, rotation: 0, height3d: 0.55, color3d: "#f5f0e8" },
//     /* bath 1 */
//     { id: "f-wc1", furnitureType: "toilet", label: "WC", x: 0.4, y: 7.35, width: 0.45, depth: 0.65, rotation: 0, height3d: 0.4, color3d: "#e8e8e8" },
//     { id: "f-basin1", furnitureType: "sink", label: "Basin", x: 2.4, y: 7.25, width: 0.6, depth: 0.45, rotation: 0, height3d: 0.85, color3d: "#e8e8e8" },
//     /* bath 2 */
//     { id: "f-wc2", furnitureType: "toilet", label: "WC", x: 8.45, y: 7.35, width: 0.45, depth: 0.65, rotation: 0, height3d: 0.4, color3d: "#e8e8e8" },
//     { id: "f-basin2", furnitureType: "sink", label: "Basin", x: 9.8, y: 7.15, width: 0.6, depth: 0.45, rotation: 0, height3d: 0.85, color3d: "#e8e8e8" },
//   ],
// };

// export const DEMO_FLOOR_PLAN: CanvasState = {
//   "meta": {
//     "version": 1,
//     "unit": "m",
//     "defaultWallHeight": 2.8,
//     "defaultWallThickness": 0.2,
//     "defaultInnerWallThickness": 0.1,
//     "slabThickness": 0.15,
//     "floorLevel": 0.01,
//     "projectName": "Villa — Variant A"
//   },
//   "rooms": [
//     {
//       "id": "bedroom1",
//       "label": "Bedroom 1",
//       "x": 0,
//       "y": 0,
//       "width": 3,
//       "height": 3.5,
//       "floor": {
//         "color": "#e8d5b7",
//         "material": "wood"
//       }
//     },
//     {
//       "id": "bedroom2",
//       "label": "Bedroom 2",
//       "x": 9,
//       "y": 0,
//       "width": 3,
//       "height": 3.5,
//       "floor": {
//         "color": "#e8d5b7",
//         "material": "wood"
//       }
//     },
//     {
//       "id": "bedroom3",
//       "label": "Bedroom 3",
//       "x": 0,
//       "y": 5,
//       "width": 4.5,
//       "height": 3,
//       "floor": {
//         "color": "#e8d5b7",
//         "material": "wood"
//       }
//     },
//     {
//       "id": "stairs",
//       "label": "Stairs",
//       "x": 8.5,
//       "y": 4.5,
//       "width": 3.5,
//       "height": 3.5,
//       "floor": {
//         "color": "#d5d5d5",
//         "material": "tile"
//       }
//     },
//     {
//       "id": "room-110",
//       "label": "Kitchen",
//       "x": 5.5,
//       "y": 5.5,
//       "width": 2.5,
//       "height": 2.5,
//       "floor": {
//         "color": "#ececec",
//         "material": "tile"
//       }
//     }
//   ],
//   "walls": [
//     {
//       "id": "ow-t",
//       "x1": 0,
//       "y1": 0,
//       "x2": 12,
//       "y2": 0,
//       "thickness": 0.2,
//       "isOuter": true,
//       "wallHeight": 2.8,
//       "wallThickness3d": 0.2
//     },
//     {
//       "id": "ow-l",
//       "x1": 0,
//       "y1": 0,
//       "x2": 0,
//       "y2": 8,
//       "thickness": 0.2,
//       "isOuter": true,
//       "wallHeight": 2.8,
//       "wallThickness3d": 0.2
//     },
//     {
//       "id": "ow-r",
//       "x1": 12,
//       "y1": 0,
//       "x2": 12,
//       "y2": 8,
//       "thickness": 0.2,
//       "isOuter": true,
//       "wallHeight": 2.8,
//       "wallThickness3d": 0.2
//     },
//     {
//       "id": "ow-b",
//       "x1": 0,
//       "y1": 8,
//       "x2": 12,
//       "y2": 8,
//       "thickness": 0.2,
//       "isOuter": true,
//       "wallHeight": 2.8,
//       "wallThickness3d": 0.2
//     }
//   ],
//   "doors": [
//     {
//       "id": "door-1",
//       "x": 0,
//       "y": 4.5,
//       "width": 0.8,
//       "height": 2.1,
//       "wallId": "",
//       "rotation": -90,
//       "type": "hinged",
//       "openDirection": "left",
//       "swingAngle": 90
//     },
//     {
//       "id": "door-4",
//       "x": 9,
//       "y": 3,
//       "width": 0.8,
//       "height": 2.1,
//       "wallId": "",
//       "rotation": 270,
//       "type": "hinged",
//       "openDirection": "right",
//       "swingAngle": 90
//     },
//     {
//       "id": "door-5",
//       "x": 12,
//       "y": 3.5,
//       "width": 0.7,
//       "height": 2.1,
//       "wallId": "",
//       "rotation": 90,
//       "type": "hinged",
//       "openDirection": "left",
//       "swingAngle": 90
//     },
//     {
//       "id": "door-111",
//       "x": 3,
//       "y": 2,
//       "width": 0.8,
//       "height": 2.0999999999999996,
//       "wallId": "ow-r",
//       "rotation": 90,
//       "type": "hinged",
//       "openDirection": "left",
//       "swingAngle": 90
//     },
//     {
//       "id": "door-112",
//       "x": 3.5,
//       "y": 5,
//       "width": 0.8,
//       "height": 2.0999999999999996,
//       "wallId": "ow-r",
//       "rotation": 0,
//       "type": "hinged",
//       "openDirection": "left",
//       "swingAngle": 90
//     },
//     {
//       "id": "door-113",
//       "x": 6.5,
//       "y": 5.5,
//       "width": 0.8,
//       "height": 2.0999999999999996,
//       "wallId": "ow-r",
//       "rotation": 0,
//       "type": "hinged",
//       "openDirection": "left",
//       "swingAngle": 90
//     }
//   ],
//   "windows": [
//     {
//       "id": "win-1",
//       "x1": 0,
//       "x2": 0,
//       "y1": 0.5,
//       "y2": 2,
//       "height": 1.2,
//       "wallId": "ow-l",
//       "sillHeight": 0.9
//     },
//     {
//       "id": "win-2",
//       "x1": 0.5,
//       "x2": 2.5,
//       "y1": 0,
//       "y2": 0,
//       "height": 1.2,
//       "wallId": "ow-t",
//       "sillHeight": 0.9
//     },
//     {
//       "id": "win-3",
//       "x1": 9,
//       "x2": 11,
//       "y1": 0,
//       "y2": 0,
//       "height": 1.2,
//       "wallId": "ow-t",
//       "sillHeight": 0.9
//     },
//     {
//       "id": "win-4",
//       "x1": 12,
//       "x2": 12,
//       "y1": 0.5,
//       "y2": 2,
//       "height": 1.2,
//       "wallId": "ow-r",
//       "sillHeight": 0.9
//     },
//     {
//       "id": "win-5",
//       "x1": 1.5,
//       "x2": 3.5,
//       "y1": 8,
//       "y2": 8,
//       "height": 1.2,
//       "wallId": "ow-b",
//       "sillHeight": 0.9
//     },
//     {
//       "id": "win-6",
//       "x1": 0,
//       "x2": 0,
//       "y1": 5.5,
//       "y2": 7,
//       "height": 1.2,
//       "wallId": "ow-l",
//       "sillHeight": 0.9
//     },
//     {
//       "id": "window-101",
//       "x1": 4.5,
//       "x2": 6,
//       "y1": 0,
//       "y2": 0,
//       "height": 1.2,
//       "wallId": "ow-r",
//       "sillHeight": 0.9
//     }
//   ],
//   "stairs": [
//     {
//       "x": 8.5,
//       "y": 4.5,
//       "id": "stairs-1",
//       "width": 3.5,
//       "height": 3.5,
//       "direction": "up"
//     }
//   ],
//   "furniture": [
//     {
//       "x": 0.5,
//       "y": 0.5,
//       "id": "furn-104",
//       "depth": 1.5,
//       "label": "Single Bed",
//       "width": 0.5,
//       "color3d": "#f5f0e8",
//       "height3d": 0.55,
//       "rotation": 0,
//       "furnitureType": "bed-single"
//     },
//     {
//       "x": 6,
//       "y": 0.5,
//       "id": "furn-105",
//       "depth": 0.9,
//       "label": "Dining Table",
//       "width": 1.6,
//       "color3d": "#a08060",
//       "height3d": 0.75,
//       "rotation": 90,
//       "furnitureType": "dining-table"
//     },
//     {
//       "x": 5,
//       "y": 1.5,
//       "id": "furn-106",
//       "depth": 0.45,
//       "label": "Chair",
//       "width": 0.45,
//       "color3d": "#7a6a5a",
//       "height3d": 0.45,
//       "rotation": 90,
//       "furnitureType": "dining-chair"
//     },
//     {
//       "x": 6.5,
//       "y": 1.5,
//       "id": "furn-107",
//       "depth": 0.45,
//       "label": "Chair",
//       "width": 0.45,
//       "color3d": "#7a6a5a",
//       "height3d": 0.45,
//       "rotation": 270,
//       "furnitureType": "dining-chair"
//     },
//     {
//       "x": 6.5,
//       "y": 2,
//       "id": "furn-108",
//       "depth": 0.45,
//       "label": "Chair",
//       "width": 0.45,
//       "color3d": "#7a6a5a",
//       "height3d": 0.45,
//       "rotation": 270,
//       "furnitureType": "dining-chair"
//     },
//     {
//       "x": 5,
//       "y": 1,
//       "id": "furn-109",
//       "depth": 0.45,
//       "label": "Chair",
//       "width": 0.45,
//       "color3d": "#7a6a5a",
//       "height3d": 0.45,
//       "rotation": 90,
//       "furnitureType": "dining-chair"
//     }
//   ]
// }

export const DEMO_FLOOR_PLAN: CanvasState = {
  "meta": {
    "version": 1,
    "unit": "m",
    "defaultWallHeight": 3.0,
    "defaultWallThickness": 0.2,
    "defaultInnerWallThickness": 0.12,
    "slabThickness": 0.15,
    "floorLevel": 0.0,
    "projectName": "Autocad-Floor-Plan"
  },
  "rooms": [],
  "walls": [
    {
      "id": "wall-1",
      "x1": 25.0,
      "y1": 22.8156,
      "x2": 21.0,
      "y2": 22.8156,
      "thickness": 0.12,
      "isOuter": false,
      "wallHeight": 3.0,
      "wallThickness3d": 0.12
    },
    {
      "id": "wall-2",
      "x1": 21.0,
      "y1": 22.8156,
      "x2": 21.0,
      "y2": 34.8156,
      "thickness": 0.12,
      "isOuter": false,
      "wallHeight": 3.0,
      "wallThickness3d": 0.12
    },
    {
      "id": "wall-3",
      "x1": 21.0,
      "y1": 34.8156,
      "x2": 32.4,
      "y2": 34.8156,
      "thickness": 0.12,
      "isOuter": false,
      "wallHeight": 3.0,
      "wallThickness3d": 0.12
    },
    {
      "id": "wall-4",
      "x1": 32.4,
      "y1": 34.8156,
      "x2": 32.4,
      "y2": 29.8156,
      "thickness": 0.12,
      "isOuter": false,
      "wallHeight": 3.0,
      "wallThickness3d": 0.12
    },
    {
      "id": "wall-5",
      "x1": 32.4,
      "y1": 29.8156,
      "x2": 33.4,
      "y2": 29.8156,
      "thickness": 0.12,
      "isOuter": false,
      "wallHeight": 3.0,
      "wallThickness3d": 0.12
    },
    {
      "id": "wall-6",
      "x1": 33.4,
      "y1": 29.8156,
      "x2": 33.4,
      "y2": 22.8156,
      "thickness": 0.12,
      "isOuter": false,
      "wallHeight": 3.0,
      "wallThickness3d": 0.12
    },
    {
      "id": "wall-7",
      "x1": 33.4,
      "y1": 22.8156,
      "x2": 28.4,
      "y2": 22.8156,
      "thickness": 0.12,
      "isOuter": false,
      "wallHeight": 3.0,
      "wallThickness3d": 0.12
    },
    {
      "id": "wall-8",
      "x1": 25.0,
      "y1": 22.5156,
      "x2": 20.7,
      "y2": 22.5156,
      "thickness": 0.2,
      "isOuter": true,
      "wallHeight": 3.0,
      "wallThickness3d": 0.2
    },
    {
      "id": "wall-9",
      "x1": 20.7,
      "y1": 22.5156,
      "x2": 20.7,
      "y2": 35.1156,
      "thickness": 0.2,
      "isOuter": true,
      "wallHeight": 3.0,
      "wallThickness3d": 0.2
    },
    {
      "id": "wall-10",
      "x1": 20.7,
      "y1": 35.1156,
      "x2": 32.7,
      "y2": 35.1156,
      "thickness": 0.2,
      "isOuter": true,
      "wallHeight": 3.0,
      "wallThickness3d": 0.2
    },
    {
      "id": "wall-11",
      "x1": 32.7,
      "y1": 35.1156,
      "x2": 32.7,
      "y2": 30.1156,
      "thickness": 0.2,
      "isOuter": true,
      "wallHeight": 3.0,
      "wallThickness3d": 0.2
    },
    {
      "id": "wall-12",
      "x1": 32.7,
      "y1": 30.1156,
      "x2": 33.7,
      "y2": 30.1156,
      "thickness": 0.2,
      "isOuter": true,
      "wallHeight": 3.0,
      "wallThickness3d": 0.2
    },
    {
      "id": "wall-13",
      "x1": 33.7,
      "y1": 30.1156,
      "x2": 33.7,
      "y2": 22.5156,
      "thickness": 0.2,
      "isOuter": true,
      "wallHeight": 3.0,
      "wallThickness3d": 0.2
    },
    {
      "id": "wall-14",
      "x1": 33.7,
      "y1": 22.5156,
      "x2": 28.4,
      "y2": 22.5156,
      "thickness": 0.2,
      "isOuter": true,
      "wallHeight": 3.0,
      "wallThickness3d": 0.2
    }
  ],
  "doors": [],
  "windows": [],
  "stairs": [],
  "furniture": []
}